--- C and C++: the compiler itself, driven through the shared keys.
---
--- No plugin does this for C, so everything here is a real invocation. The one thing
--- that matters more than the commands is the *flags*: preprocessing or compiling a
--- kernel source file with default flags produces nonsense, because it needs the
--- include paths and defines the build system passes. So every command that touches
--- the compiler reads `compile_commands.json` first, which is exactly what clangd is
--- already using to understand the file.
---@class lang.c
local M = {}

--- Titles this adapter renders under, so the keymap can ask whether a view is
--- already on screen. Declared beside the code that uses them: a central table
--- drifts the moment an adapter gains a capability.
---@type table<string, string>
M.titles = {
	expand = "c preprocessed",
	assembly = "c asm",
	ir = "c llvm-ir",
	tree = "c ast",
	check = "c check",
}

local output = require("features.lang.output")
local root = require("lib.root")

--- Project root, by build system.
---@param buf integer
---@return string
local function project(buf)
	return root.detectors.pattern(buf, { "compile_commands.json", "CMakeLists.txt", "Makefile", "meson.build" })[1]
		or root.get({ buf = buf })
end

--- The compile command recorded for a file, split into argv.
---
--- Without this, preprocessing anything from a real project fails on the first
--- `#include` it cannot find. `compile_commands.json` is generated by cmake, meson,
--- bear or the kernel's own `make compile_commands.json`.
---@param buf integer
---@return string[]? argv, string? dir
local function compile_command(buf)
	local dir = root.detectors.pattern(buf, "compile_commands.json")[1]
	if not dir then
		return nil
	end
	local ok, content = pcall(vim.fn.readfile, vim.fs.joinpath(dir, "compile_commands.json"))
	if not ok then
		return nil
	end
	local decoded, db = pcall(vim.json.decode, table.concat(content, "\n"))
	if not decoded or type(db) ~= "table" then
		return nil
	end

	local target = vim.fs.normalize(vim.api.nvim_buf_get_name(buf))
	for _, entry in ipairs(db) do
		local file = vim.fs.normalize(entry.file or "")
		if file == target or file:sub(-#target) == target then
			local argv = entry.arguments
			if not argv and entry.command then
				argv = vim.split(entry.command, "%s+")
			end
			return argv, entry.directory or dir
		end
	end
	return nil
end

--- Compiler flags for a file: the recorded ones with the output and compile-only
--- switches stripped, or a bare fallback when the project has no database.
---@param buf integer
---@param extra string[] Flags for the mode being asked for (-E, -S, …)
---@return string[] cmd, string dir, boolean from_db
local function invocation(buf, extra)
	local path = vim.api.nvim_buf_get_name(buf)
	local argv, dir = compile_command(buf)

	if not argv then
		-- No database. Still useful for a single self-contained file, and honest about
		-- what it cannot do for anything that includes the project's headers.
		local cc = vim.fn.executable("clang") == 1 and "clang" or "cc"
		return vim.list_extend({ cc }, vim.list_extend(vim.deepcopy(extra), { path })), project(buf), false
	end

	local normalized = vim.fs.normalize(path)
	local basename = vim.fn.fnamemodify(path, ":t")

	local cmd = {}
	local skip_next = false
	for _, arg in ipairs(argv) do
		if skip_next then
			skip_next = false
		elseif arg == "-o" or arg == "-MF" or arg == "-MT" or arg == "-MQ" then
			-- Drop the flag and its operand: writing to the recorded object path would
			-- overwrite a real build artefact.
			skip_next = true
		elseif arg == "-c" or arg == "-S" or arg == "-E" or arg:match("^%-M") then
			-- The mode is being replaced by `extra`.
		elseif vim.fs.normalize(arg) == normalized or arg == basename then
			-- The source file, wherever it sits in the recorded command. Databases put
			-- it before `-o`, not last, so matching only the final argument left it in
			-- and the file was compiled twice.
		else
			table.insert(cmd, arg)
		end
	end

	vim.list_extend(cmd, extra)
	table.insert(cmd, path)
	return cmd, dir or project(buf), true
end

--- Exposed for features/sys, which compiles with the same flags for pahole.
M.invocation = invocation

--- Notifies when output came from a guess rather than the project's own flags, since
--- that is the difference between real preprocessor output and something misleading.
---@param from_db boolean
local function warn_flags(from_db)
	if not from_db then
		Snacks.notify.warn(
			"No compile_commands.json; using default flags.\nProject includes and defines are missing.",
			{ title = "C" }
		)
	end
end

--- Build, by whichever build system the project uses.
---@param buf integer
function M.build(buf)
	local dir = project(buf)
	local ninja = vim.uv.fs_stat(vim.fs.joinpath(dir, "build.ninja"))
	local cmake = vim.uv.fs_stat(vim.fs.joinpath(dir, "CMakeLists.txt"))
	local meson = vim.uv.fs_stat(vim.fs.joinpath(dir, "meson.build"))

	if ninja then
		output.terminal({ "ninja" }, dir, { title = "ninja" })
	elseif meson then
		output.terminal({ "meson", "compile", "-C", "build" }, dir, { title = "meson compile" })
	elseif cmake then
		output.terminal({ "cmake", "--build", "build" }, dir, { title = "cmake --build" })
	else
		-- `make` with no target, which is what a kernel tree and most makefiles want.
		output.terminal({ "make", "-j" .. tostring(vim.uv.available_parallelism()) }, dir, { title = "make" })
	end
end

--- Runs one of the project's binaries, asking which the first time and remembering it.
---
--- Not `make run`: plenty of projects have no such target, and a kernel tree certainly
--- does not. Finding the ELF files that were actually built is a question with an
--- answer, unlike guessing a target name.
---@param buf integer
---@param opts? { reselect?: boolean }
function M.run(buf, opts)
	local dir = project(buf)
	require("features.lang.binary").select(dir, opts, function(path)
		output.terminal({ path }, dir, { title = vim.fn.fnamemodify(path, ":t") })
	end)
end

--- Forgets the remembered binary and asks again.
---@param buf integer
function M.run_other(buf)
	M.run(buf, { reselect = true })
end

---@param buf integer
function M.test(buf)
	local dir = project(buf)
	if vim.uv.fs_stat(vim.fs.joinpath(dir, "build", "CTestTestfile.cmake")) then
		output.terminal({ "ctest", "--test-dir", "build", "--output-on-failure" }, dir, { title = "ctest" })
	else
		output.terminal({ "make", "test" }, dir, { title = "make test" })
	end
end

--- Syntax and semantic check of this file alone, no codegen and no output file.
---@param buf integer
function M.check(buf)
	local cmd, dir, from_db = invocation(buf, { "-fsyntax-only" })
	warn_flags(from_db)
	output.run({ cmd = cmd, title = M.titles.check, cwd = dir, filetype = "qf" })
end

---@param buf integer
function M.build_file(buf)
	local dir = project(buf)
	for _, name in ipairs({ "CMakeLists.txt", "meson.build", "Makefile", "makefile", "GNUmakefile" }) do
		local path = vim.fs.joinpath(dir, name)
		if vim.uv.fs_stat(path) then
			vim.cmd.edit(path)
			return
		end
	end
	Snacks.notify.warn("No build file found in " .. dir, { title = "C" })
end

--- Preprocessor output: every macro expanded, every include pulled in.
---
--- The single most useful view in kernel C, where a call is as likely to be three
--- layers of macro as it is a function.
---@param buf integer
function M.expand(buf)
	local cmd, dir, from_db = invocation(buf, { "-E", "-P" })
	warn_flags(from_db)
	output.run({ cmd = cmd, title = M.titles.expand, filetype = "c", cwd = dir })
end

--- Assembly, at the optimisation level the project actually builds with.
---@param buf integer
function M.assembly(buf)
	local cmd, dir, from_db = invocation(buf, {
		"-S",
		"-o",
		"-",
		-- Intel syntax and no directive noise: what is left is the instructions.
		"-masm=intel",
		"-fno-asynchronous-unwind-tables",
		"-fno-dwarf2-cfi-asm",
		-- Debug info even when the project builds without it: `.loc` markers are what
		-- links each instruction back to the line that produced it. They are consumed
		-- by the filter, not shown, so this costs nothing to read.
		"-g",
	})
	warn_flags(from_db)
	output.run({
		cmd = cmd,
		title = M.titles.assembly,
		filetype = "asm",
		cwd = dir,
		on_lines = output.strip_asm,
	})
end

--- LLVM IR, which sits between the source and the assembly and is far easier to read
--- when the question is what the optimiser did rather than what the CPU will run.
---@param buf integer
function M.ir(buf)
	if not output.require_exe("clang") then
		return
	end
	local cmd, dir, from_db = invocation(buf, { "-S", "-emit-llvm", "-o", "-", "-g" })
	cmd[1] = "clang"
	warn_flags(from_db)
	output.run({ cmd = cmd, title = M.titles.ir, filetype = "llvm", cwd = dir })
end

--- Clang's AST, for when the question is how the compiler parsed something.
---@param buf integer
function M.tree(buf)
	if not output.require_exe("clang") then
		return
	end
	local cmd, dir, from_db = invocation(buf, { "-Xclang", "-ast-dump", "-fsyntax-only" })
	cmd[1] = "clang"
	warn_flags(from_db)
	output.run({ cmd = cmd, title = M.titles.tree, cwd = dir })
end

--- Header to source and back, which clangd computes from the compilation database.
---@param buf integer
function M.related(buf)
	local client = vim.lsp.get_clients({ bufnr = buf, name = "clangd" })[1]
	if not client then
		Snacks.notify.warn("clangd is not attached", { title = "C" })
		return
	end
	client:request("textDocument/switchSourceHeader", vim.lsp.util.make_text_document_params(buf), function(err, uri)
		if err or not uri then
			Snacks.notify.warn("No matching header or source", { title = "C" })
			return
		end
		vim.cmd.edit(vim.uri_to_fname(uri))
	end, buf)
end

return M
